version: 0.2
phases:
  install:
    commands:
      - export TerraformVersion=0.15 && cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/${TerraformVersion}/terraform_${TerraformVersion}_linux_amd64.zip && unzip terraform.zip && mv terraform /usr/bin
  build:
    commands:
      - terraform init && terraform plan && echo terraform apply